export const appConstants = {
  SET_ROWS: "SET_ROWS",
  SET_VALID_HEADERS: "SET_VALID_HEADERS",
  SET_HEADER: "SET_HEADER",
  IGNORE_COLUMN: "IGNORE_COLUMN",
  RECONSIDER_COLUMN: "RECONSIDER_COLUMN",
  SET_GRID_ROWS: "SET_GRID_ROWS",
};
